version: '3.3'

services:
  nginx:
    build: ./server/nginx/.
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ".:${PROJECT_DIR}"
    links:
      - php
  php:
    build: ./server/php/.
    env_file:
      - .env
    volumes:
      - ".:${PROJECT_DIR}"
      - ./server/php/tmp:/tmp
  composer:
    build: ./server/composer/.
    restart: 'no'
    command:
      - install
    volumes:
      - .:/app

